# Gwork Travis config

# Use Ubuntu Trusty (14) for mostly up-to-date packages
sudo: required
dist: trusty
language: cpp

# Travis compilers are out of date if we want to use modern C++1y features. Need to
# explicitly specify external packages required and versions in matrix.
# Problems for earlier compilers include <codecvt> coverage on GCC.
#
# More info: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
# matrix example: https://github.com/ColinH/PEGTL/blob/master/.travis.yml
#
# currently issue for adding the Trusty LLVM ppa to Travis’ whitelist, previous, 12.04
# issue: https://github.com/travis-ci/apt-source-whitelist/pull/205
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9            
      env: COMPILER=g++-4.9 BUILD_CONFIG=Debug 
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - doxygen
      env: COMPILER=g++-5 BUILD_CONFIG=Debug 
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - doxygen
      env: COMPILER=g++-6 BUILD_CONFIG=Debug 
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6 BUILD_CONFIG=Debug 
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7 BUILD_CONFIG=Debug 
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - doxygen
      env: COMPILER=clang++-3.8 BUILD_CONFIG=Debug 
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER=clang++ BUILD_CONFIG=Debug
      install: ./ci/travis/install.sh
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: COMPILER=clang++ BUILD_CONFIG=Release
      install: ./ci/travis/install.sh
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: COMPILER=clang++ BUILD_CONFIG=Release WANTS="-DWANT_REFLECTION=ON"
      install: ./ci/travis/install.sh
      
# install: ./ci/travis/install.sh
  
before_script: ./ci/travis/make_build.sh $COMPILER "$WANTS"
    
script:
  - cd build && cmake --build . --target GworkNullSample --config $BUILD_CONFIG

notifications:
  email:
    on_failure: change
    on_success: change
